// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/explain": {
            "post": {
                "description": "Explain architecture from image + prompt. Image is sent as base64 string in JSON.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "explain"
                ],
                "summary": "Explain diagram image",
                "parameters": [
                    {
                        "description": "Explain request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExplainRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ExplainResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/explain/stream": {
            "post": {
                "description": "Stream explanation tokens from image + prompt. Image is sent as base64 string in JSON.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "explain"
                ],
                "summary": "Stream explanation",
                "parameters": [
                    {
                        "description": "Explain request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExplainRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Stream of tokens (SSE)",
                        "schema": {
                            "$ref": "#/definitions/models.StreamChunk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ExplainRequest": {
            "type": "object",
            "properties": {
                "file_base64": {
                    "type": "string",
                    "example": "iVBORw0KGgoAAAANSUhEUgAA..."
                },
                "file_format": {
                    "type": "string",
                    "example": "png"
                },
                "file_name": {
                    "type": "string",
                    "example": "diagram.png"
                },
                "generation": {
                    "description": "Optional generation parameters",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.GenerationParams"
                        }
                    ]
                },
                "prompt": {
                    "type": "string",
                    "example": "Explain architecture"
                }
            }
        },
        "models.ExplainResponse": {
            "type": "object",
            "properties": {
                "explanation": {
                    "type": "string"
                }
            }
        },
        "models.GenerationParams": {
            "type": "object",
            "properties": {
                "max_tokens": {
                    "type": "integer",
                    "default": 512,
                    "example": 512
                },
                "temperature": {
                    "type": "number",
                    "default": 0.7,
                    "example": 0.7
                }
            }
        },
        "models.StreamChunk": {
            "type": "object",
            "properties": {
                "delta": {
                    "type": "string"
                },
                "explanation": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
